name=input("What's your name?") 
print("Name saved✅")
birthyear=int(input("Which year were you born?"))
home=input("Where do you live?")
tribe=("What's your tribe")
university=input("Which university are you studying from?")
college=input("Which college are you studying from?")
department=("Which department within the college are you into?")
program=("Which course in the department are you into ?")
contact1=input("What is your phone number?")
contact2=input("What's your parent's phone number ?")
email=input("What's your email address?")

